name: Add Reaction

on:
  repository_dispatch:
    types:
    - add-reaction-command

jobs:
  example:
    name: test1
    runs-on: ubuntu-latest
    steps:
    - name: add reaction
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.MY_GITHUB_TOKEN }}
        comment-id: ${{ github.event.client-payload.github.payload.comment.id }}
        reaction-type: hooray
