# https://github.com/marketplace/actions/find-comment
name: Find Comment Test

on:
  issue_comment:
    types:
    - created

jobs:
  job1:
    name: test1
    runs-on: ubuntu-latest
    steps:
    - name: Find Comment
      uses: peter-evans/find-comment@v1
      id: fc1
      with:
        # token: ${{ secrets.MY_GITHUB_TOKEN }}
        issue-number: 1
        body-includes: /test1
    - run: |
        echo ${{ steps.fc1.outputs.comment-id }}
        echo ${{ steps.fc1.outputs.comment-body }}
        echo ${{ steps.fc1.outputs.comment-author }}
        echo ${{ github.event.issue.number }}
        
